"""
Deutscht die 277 Rubriken ein, die noch OMRs englische Namen und Slugs tragen.

Warum Name UND Slug: Der Slug ist bei uns der URL-Pfad. Uebernaehmen wir OMRs
kanonische Bezeichner, wuerden unsere URLs deren Taxonomie spiegeln, erkennbar
fuer OMR und fuer Google. Nichts davon ist live, die Slugs sind noch frei.
Nach Livegang waere das irreversibel (Slugs sind stabil).

Schreibt die Spalten `rubrik_final` und `slug_final` in die CSV.
"""
import csv, re, sys

# slug (alt) -> (deutscher Name, neuer Slug). Slug = None -> bleibt unveraendert.
M = {
 "a-b-testing": ("A/B-Testing", "a-b-testing"),
 "ad-network": ("Werbenetzwerke", "werbenetzwerke"),
 "affiliate-networks": ("Affiliate-Netzwerke", "affiliate-netzwerke"),
 "affiliate-platform": ("Affiliate-Plattformen", "affiliate-plattformen"),
 "ai": ("Künstliche Intelligenz", "kuenstliche-intelligenz"),
 "ai-agent-builders": ("KI-Agenten-Baukästen", "ki-agenten-baukaesten"),
 "ai-agents": ("KI-Agenten", "ki-agenten"),
 "ai-agents-for-business-operations": ("KI-Agenten für Geschäftsprozesse", "ki-agenten-fuer-geschaeftsprozesse"),
 "ai-browser": ("KI-Browser", "ki-browser"),
 "ai-call-assistant": ("KI-Telefonassistenten", "ki-telefonassistenten"),
 "ai-chatbots": ("KI-Chatbots", "ki-chatbots"),
 "ai-code-generation": ("KI-Codegenerierung", "ki-codegenerierung"),
 "ai-coding-assistants": ("KI-Programmierassistenten", "ki-programmierassistenten"),
 "ai-compliance": ("KI-Compliance", "ki-compliance"),
 "ai-customer-support-agents": ("KI-Agenten für den Kundensupport", "ki-agenten-fuer-den-kundensupport"),
 "ai-detection": ("KI-Erkennung", "ki-erkennung"),
 "ai-meeting-assistants": ("KI-Meeting-Assistenten", "ki-meeting-assistenten"),
 "ai-model-hosting": ("KI-Modell-Hosting", "ki-modell-hosting"),
 "ai-sales-personalization": ("KI-Vertriebspersonalisierung", "ki-vertriebspersonalisierung"),
 "ai-sales-roleplay": ("KI-Verkaufstraining", "ki-verkaufstraining"),
 "ai-sdr": ("KI-Vertriebsassistenten", "ki-vertriebsassistenten"),
 "ai-video-generation": ("KI-Videogenerierung", "ki-videogenerierung"),
 "amazon-marketing": ("Amazon-Marketing", "amazon-marketing"),
 "amazon-ppc": ("Amazon-PPC", "amazon-ppc"),
 "antivirus": ("Virenschutz", "virenschutz"),
 "audio-plugins": ("Audio-Plugins", "audio-plugins"),
 "audit-management": ("Auditmanagement", "auditmanagement"),
 "b2b-e-commerce-platforms-shop-systems": ("B2B-Shopsysteme", "b2b-shopsysteme"),
 "backlink": ("Backlinks", "backlinks"),
 "backlink-analysis": ("Backlink-Analyse", "backlink-analyse"),
 "backlink-check": ("Backlink-Check", "backlink-check"),
 "backlink-monitoring": ("Backlink-Überwachung", "backlink-ueberwachung"),
 "bau-projektmanagement": ("Bau-Projektmanagement", None),
 "billing": ("Abrechnung", "abrechnung"),
 "buchhaltung-fuer-vereine": ("Buchhaltung für Vereine", None),
 "budgeting-and-forecasting": ("Budgetierung und Forecast", "budgetierung-und-forecast"),
 "business-account": ("Geschäftskonten", "geschaeftskonten"),
 "business-intelligence-platforms": ("Business-Intelligence-Plattformen", "business-intelligence-plattformen"),
 "call-center-infrastructure-cci": ("Callcenter-Infrastruktur", "callcenter-infrastruktur"),
 "cannabis-social-club": ("Cannabis-Social-Club-Verwaltung", "cannabis-social-club-verwaltung"),
 "carbon-accounting": ("CO2-Bilanzierung", "co2-bilanzierung"),
 "cash-flow-management": ("Liquiditätsmanagement", "liquiditaetsmanagement"),
 "cloud-content-collaboration": ("Cloud-Zusammenarbeit", "cloud-zusammenarbeit"),
 "cloud-data-security": ("Cloud-Datensicherheit", "cloud-datensicherheit"),
 "cloud-erp": ("Cloud-ERP", "cloud-erp"),
 "cloud-web-hosting": ("Cloud-Hosting", "cloud-hosting"),
 "community-management": ("Community-Management", "community-management"),
 "consent-management-platform-cmp": ("Consent-Management-Plattformen", "consent-management-plattformen"),
 "content-creation": ("Content-Erstellung", "content-erstellung"),
 "content-management-systems-cms": ("Content-Management-Systeme", "content-management-systeme-cms"),
 "content-recommendation": ("Content-Empfehlung", "content-empfehlung"),
 "contract-analytics": ("Vertragsanalyse", "vertragsanalyse"),
 "conversational-intelligence": ("Gesprächsanalyse", "gespraechsanalyse"),
 "conversational-marketing": ("Conversational Marketing", "conversational-marketing"),
 "conversion-optimization": ("Conversion-Optimierung", "conversion-optimierung"),
 "conversion-tracking": ("Conversion-Tracking", "conversion-tracking"),
 "core-hr": ("Personalstammdaten", "personalstammdaten"),
 "corporate-learning-management-systems": ("Lernmanagement für Unternehmen", "lernmanagement-fuer-unternehmen"),
 "corporate-sustainability-reporting-directive-csrd": ("CSRD-Berichterstattung", "csrd-berichterstattung"),
 "crm": ("CRM", "crm"),
 "cross-channel-advertising": ("Kanalübergreifende Werbung", "kanaluebergreifende-werbung"),
 "crypto-accounting": ("Krypto-Buchhaltung", "krypto-buchhaltung"),
 "customer-data-platforms-cdp": ("Customer-Data-Plattformen", "customer-data-plattformen-cdp"),
 "customer-journey-analytics": ("Customer-Journey-Analyse", "customer-journey-analyse"),
 "customer-journey-mapping": ("Customer-Journey-Mapping", "customer-journey-mapping"),
 "data-cloud": ("Data Cloud", "data-cloud"),
 "data-management-platforms-dmp": ("Data-Management-Plattformen", "data-management-plattformen-dmp"),
 "data-storage": ("Datenspeicher", "datenspeicher"),
 "datenschutz-management": ("Datenschutzmanagement", None),
 "daw": ("Digitale Audio-Workstations", "digitale-audio-workstations"),
 "design": ("Design", "design"),
 "diagramming": ("Diagramme", "diagramme"),
 "dienstleister-erp": ("ERP für Dienstleister", "erp-fuer-dienstleister"),
 "digital-business-card": ("Digitale Visitenkarten", "digitale-visitenkarten"),
 "digital-process-automation-dpa": ("Digitale Prozessautomatisierung", "digitale-prozessautomatisierung"),
 "digital-rights-management-drm": ("Digitales Rechtemanagement", "digitales-rechtemanagement"),
 "digital-sales-room": ("Digitale Verkaufsräume", "digitale-verkaufsraeume"),
 "digital-shelf-analytics-dsa": ("Digital-Shelf-Analyse", "digital-shelf-analyse"),
 "diversity-recruiting": ("Diversity-Recruiting", "diversity-recruiting"),
 "dokumentenmanagement": ("Dokumentenmanagement", None),
 "domain-registration": ("Domainregistrierung", "domainregistrierung"),
 "donor-management": ("Spenderverwaltung", "spenderverwaltung"),
 "drawing": ("Zeichnen", "zeichnen"),
 "e-commerce-analytics": ("E-Commerce-Analyse", "e-commerce-analyse"),
 "e-commerce-personalization": ("E-Commerce-Personalisierung", "e-commerce-personalisierung"),
 "e-invoice": ("E-Rechnung", "e-rechnung"),
 "e-mail": ("E-Mail", "e-mail"),
 "e-mail-deliverability": ("E-Mail-Zustellbarkeit", "e-mail-zustellbarkeit"),
 "e-signature": ("Elektronische Signatur", "elektronische-signatur"),
 "einkauf": ("Einkauf", None),
 "elearning-content": ("E-Learning-Inhalte", "e-learning-inhalte"),
 "email-template-builder": ("E-Mail-Vorlagen-Builder", "e-mail-vorlagen-builder"),
 "employee-benefits": ("Mitarbeiter-Benefits", "mitarbeiter-benefits"),
 "employee-communications": ("Mitarbeiterkommunikation", "mitarbeiterkommunikation-plattformen"),
 "employer-branding": ("Employer Branding", "employer-branding"),
 "endpoint-detection-response-edr": ("Endpoint Detection and Response", "endpoint-detection-and-response"),
 "endpoint-management": ("Endpoint-Management", "endpoint-management"),
 "endpoint-protection-platforms": ("Endpoint-Schutz", "endpoint-schutz"),
 "enterprise-content-management-ecm": ("Enterprise Content Management", "enterprise-content-management-ecm"),
 "enterprise-information-archiving": ("Informationsarchivierung", "informationsarchivierung"),
 "enterprise-legal-management-elm": ("Rechtsabteilungs-Management", "rechtsabteilungs-management"),
 "environmental-social-and-governance-esg-reporting": ("ESG-Berichterstattung", "esg-berichterstattung"),
 "erp-systems": ("ERP-Systeme", "erp-systeme-uebersicht"),
 "expense-management": ("Ausgabenmanagement", "ausgabenmanagement"),
 "experience-management": ("Experience Management", "experience-management"),
 "fensterbau-fassadenbau-erp": ("ERP für Fenster- und Fassadenbau", "erp-fuer-fenster-und-fassadenbau"),
 "financial-analytics": ("Finanzanalyse", "finanzanalyse"),
 "fleet-tracking": ("Fahrzeugortung", "fahrzeugortung"),
 "freelance-platforms": ("Freelancer-Plattformen", "freelancer-plattformen"),
 "freelance-tax": ("Steuer für Selbstständige", "steuer-fuer-selbststaendige"),
 "frontend-management-platforms": ("Frontend-Management-Plattformen", "frontend-management-plattformen"),
 "funnel-builder": ("Funnel-Builder", "funnel-builder"),
 "gastronomy": ("Gastronomie", "gastronomie"),
 "generative-engine-optimization-geo": ("Generative Engine Optimization", "generative-engine-optimization-geo"),
 "governance-risk-compliance": ("Governance, Risiko und Compliance", "governance-risiko-und-compliance"),
 "grosshandel-erp": ("ERP für den Großhandel", "erp-fuer-den-grosshandel"),
 "handwerk-erp": ("ERP für das Handwerk", "erp-fuer-das-handwerk"),
 "headless-cms": ("Headless CMS", "headless-cms"),
 "helpdesk": ("Helpdesk", "helpdesk"),
 "hr-management": ("Personalmanagement", "personalmanagement"),
 "hr-service-delivery": ("HR-Serviceportale", "hr-serviceportale"),
 "hr-workflow-management": ("HR-Workflow-Management", "hr-workflow-management"),
 "human-resource-management-systems": ("Personalmanagement-Systeme", "personalmanagement-systeme"),
 "inbound-call-tracking": ("Anruf-Tracking", "anruf-tracking"),
 "installment-payment-and-buy-now-pay-later-bnpl": ("Ratenzahlung und Buy Now, Pay Later", "ratenzahlung-und-buy-now-pay-later"),
 "instant-messaging": ("Instant Messaging", "instant-messaging"),
 "integration-brokerage": ("Integrations-Brokerage", "integrations-brokerage"),
 "intelligent-document-processing-idp": ("Intelligente Dokumentenverarbeitung", "intelligente-dokumentenverarbeitung"),
 "invoice-management": ("Rechnungsmanagement", "rechnungsmanagement"),
 "it-dienstleister-erp": ("ERP für IT-Dienstleister", "erp-fuer-it-dienstleister"),
 "it-risk-management": ("IT-Risikomanagement", "it-risikomanagement"),
 "it-service-management-itsm": ("IT-Service-Management", "it-service-management-itsm"),
 "keyword": ("Keywords", "keywords"),
 "keyword-mapping": ("Keyword-Mapping", "keyword-mapping"),
 "keyword-monitoring": ("Keyword-Überwachung", "keyword-ueberwachung"),
 "keyword-rank-tracking": ("Ranking-Überwachung", "ranking-ueberwachung"),
 "keyword-research": ("Keyword-Recherche", "keyword-recherche"),
 "ki-text-generator": ("KI-Textgeneratoren", "ki-textgeneratoren"),
 "kunststoffverarbeitung-erp": ("ERP für die Kunststoffverarbeitung", "erp-fuer-die-kunststoffverarbeitung"),
 "lager-logistik-erp": ("ERP für Lager und Logistik", "erp-fuer-lager-und-logistik"),
 "landing-page-builders": ("Landingpage-Builder", "landingpage-builder"),
 "lead-intelligence": ("Lead Intelligence", "lead-intelligence"),
 "learning-experience-platforms-lxp": ("Learning-Experience-Plattformen", "learning-experience-plattformen-lxp"),
 "learning-management-systems": ("Lernmanagement-Systeme", "lernmanagement-systeme"),
 "lebensmittelindustrie-erp": ("ERP für die Lebensmittelindustrie", "erp-fuer-die-lebensmittelindustrie"),
 "lieferkettensorgfaltspflichtengesetz-csddd": ("Lieferkettensorgfaltspflichten", "lieferkettensorgfaltspflichten"),
 "linkbuilding": ("Linkbuilding", "linkbuilding"),
 "linkedin-automation": ("LinkedIn-Automatisierung", "linkedin-automatisierung"),
 "live-stream": ("Livestreaming", "livestreaming"),
 "local-marketing": ("Lokales Marketing", "lokales-marketing"),
 "local-seo": ("Local SEO", "local-seo"),
 "logistics-intelligence": ("Logistik-Analyse", "logistik-analyse"),
 "loyalty-management": ("Kundenbindungsmanagement", "kundenbindungsmanagement"),
 "managed-hosting": ("Managed Hosting", "managed-hosting"),
 "market-intelligence": ("Marktanalyse", "marktanalyse"),
 "marketing-operations-platforms": ("Marketing-Operations-Plattformen", "marketing-operations-plattformen"),
 "marketing-platforms": ("Marketing-Plattformen", "marketing-plattformen"),
 "marketing-resource-management": ("Marketing-Ressourcen-Management", "marketing-ressourcen-management"),
 "marktplatz": ("Marktplätze", "marktplaetze"),
 "maschinenbau-anlagenbau-erp": ("ERP für Maschinen- und Anlagenbau", "erp-fuer-maschinen-und-anlagenbau"),
 "media-monitoring": ("Medienbeobachtung", "medienbeobachtung"),
 "medizintechnik-erp": ("ERP für die Medizintechnik", "erp-fuer-die-medizintechnik"),
 "meeting-management": ("Meeting-Management", "meeting-management"),
 "mobile-development-platforms": ("Plattformen für App-Entwicklung", "plattformen-fuer-app-entwicklung"),
 "mobile-device-management-mdm": ("Mobile Device Management", "mobile-device-management-mdm"),
 "mobile-wallet-service": ("Mobile Wallets", "mobile-wallets"),
 "multichannel-retail": ("Multichannel-Handel", "multichannel-handel"),
 "natural-language-understanding-nlu": ("Sprachverstehen (NLU)", "sprachverstehen-nlu"),
 "no-code-development-platform": ("No-Code-Plattformen", "no-code-plattformen"),
 "office-suites": ("Office-Pakete", "office-pakete"),
 "online-reputation-management": ("Reputationsmanagement", "reputationsmanagement"),
 "onlineshop-buchhaltung": ("Buchhaltung für Onlineshops", "buchhaltung-fuer-onlineshops"),
 "onpage": ("Onpage-Optimierung", "onpage-optimierung"),
 "onsite-search": ("Suche für die eigene Website", "suche-fuer-die-eigene-website"),
 "optical-character-recognition-ocr": ("Texterkennung (OCR)", "texterkennung-ocr"),
 "organigramm": ("Organigramme", "organigramme"),
 "other-conversion-optimization": ("Weitere Conversion-Optimierung", "weitere-conversion-optimierung"),
 "p2c": ("Procure-to-Cash", "procure-to-cash"),
 "pagespeed": ("Ladezeit-Optimierung", "ladezeit-optimierung"),
 "passwortmanagement": ("Passwortmanagement", None),
 "payment": ("Zahlungsabwicklung", "zahlungsabwicklung"),
 "payment-method": ("Zahlungsarten", "zahlungsarten"),
 "pc-backup": ("PC-Backup", "pc-backup"),
 "pharma-erp": ("ERP für die Pharmaindustrie", "erp-fuer-die-pharmaindustrie"),
 "photo-management": ("Fotoverwaltung", "fotoverwaltung"),
 "podcast": ("Podcast", "podcast"),
 "press-release-distribution": ("Pressemitteilungs-Verteiler", "pressemitteilungs-verteiler"),
 "pricing": ("Preisgestaltung", "preisgestaltung"),
 "print-marketing": ("Print-Marketing", "print-marketing"),
 "print-on-demand": ("Print-on-Demand", "print-on-demand"),
 "private-affiliate-networks": ("Private Affiliate-Netzwerke", "private-affiliate-netzwerke"),
 "process-mining": ("Process Mining", "process-mining"),
 "product-data-management-pdm": ("Produktdatenmanagement", "produktdatenmanagement-pdm"),
 "product-feed-management": ("Produktdaten-Feeds", "produktdaten-feeds"),
 "product-information-management-pim": ("Produktinformations-Management", "produktinformations-management-pim"),
 "produktion-fertigung-erp": ("ERP für Produktion und Fertigung", "erp-fuer-produktion-und-fertigung"),
 "project-collaboration": ("Projekt-Zusammenarbeit", "projekt-zusammenarbeit"),
 "project-time-tracking": ("Projektzeiterfassung", "projektzeiterfassung"),
 "prozessmanagement": ("Prozessmanagement", None),
 "public-affiliate-networks": ("Öffentliche Affiliate-Netzwerke", "oeffentliche-affiliate-netzwerke"),
 "public-relations-pr": ("Öffentlichkeitsarbeit (PR)", "oeffentlichkeitsarbeit-pr"),
 "publisher-ad-management": ("Werbevermarktung für Publisher", "werbevermarktung-fuer-publisher"),
 "push-notification": ("Push-Benachrichtigungen", "push-benachrichtigungen"),
 "recruiting-automation": ("Recruiting-Automatisierung", "recruiting-automatisierung"),
 "recruitment-marketing": ("Recruiting-Marketing", "recruiting-marketing"),
 "recruitment-platforms": ("Recruiting-Plattformen", "recruiting-plattformen"),
 "relational-databases": ("Relationale Datenbanken", "relationale-datenbanken"),
 "remote-monitoring-management-rmm": ("Remote Monitoring and Management", "remote-monitoring-and-management-rmm"),
 "retargeting": ("Retargeting", "retargeting"),
 "retrieval-augmented-generation": ("Retrieval Augmented Generation", "retrieval-augmented-generation"),
 "revenue-operations-intelligence-ro-i": ("Revenue-Operations-Analyse", "revenue-operations-analyse"),
 "saas-operations-management": ("SaaS-Betriebsmanagement", "saas-betriebsmanagement"),
 "saas-spend-management": ("SaaS-Kostenmanagement", "saas-kostenmanagement"),
 "sales": ("Vertrieb", "vertrieb"),
 "sales-analytics": ("Vertriebsanalyse", "vertriebsanalyse"),
 "sales-compensation": ("Vertriebsvergütung", "vertriebsverguetung"),
 "sales-engagement": ("Sales Engagement", "sales-engagement"),
 "sales-platforms": ("Vertriebsplattformen", "vertriebsplattformen"),
 "sales-tax-and-vat-compliance": ("Umsatzsteuer-Compliance", "umsatzsteuer-compliance"),
 "search-engine-advertising": ("Suchmaschinenwerbung (SEA)", "suchmaschinenwerbung-sea"),
 "sentiment-analysis": ("Stimmungsanalyse", "stimmungsanalyse"),
 "seo-analysis": ("SEO-Analyse", "seo-analyse"),
 "seo-audit": ("SEO-Audit", "seo-audit"),
 "seo-browser-plugins": ("SEO-Browser-Plugins", "seo-browser-plugins"),
 "seo-competitor-analysis": ("SEO-Wettbewerbsanalyse", "seo-wettbewerbsanalyse"),
 "seo-content": ("SEO-Content", "seo-content"),
 "seo-reporting": ("SEO-Reporting", "seo-reporting"),
 "seo-suites": ("SEO-Suiten", "seo-suiten"),
 "serp-overlap": ("SERP-Überschneidung", "serp-ueberschneidung"),
 "social-customer-service": ("Kundenservice über Social Media", "kundenservice-ueber-social-media"),
 "social-intranet": ("Social Intranet", "social-intranet"),
 "social-media-advertising": ("Social-Media-Werbung", "social-media-werbung"),
 "social-media-analyse": ("Social-Media-Analyse", "social-media-analyse"),
 "social-media-engagement": ("Social-Media-Engagement", "social-media-engagement"),
 "social-media-listening": ("Social Listening", "social-listening"),
 "social-media-planung": ("Social-Media-Planung", "social-media-planung"),
 "social-media-suites": ("Social-Media-Suiten", "social-media-suiten"),
 "start-up-erp": ("ERP für Start-ups", "erp-fuer-start-ups"),
 "strategic-planning-and-execution": ("Strategieplanung und Umsetzung", "strategieplanung-und-umsetzung"),
 "supplier-relationship-management": ("Lieferantenmanagement", "lieferantenmanagement"),
 "supply-chain-business-networks": ("Supply-Chain-Netzwerke", "supply-chain-netzwerke"),
 "supply-chain-cost-to-serve-analytics": ("Supply-Chain-Kostenanalyse", "supply-chain-kostenanalyse"),
 "supply-chain-logistik": ("Supply-Chain-Logistik", "supply-chain-logistik"),
 "supply-chain-planning": ("Supply-Chain-Planung", "supply-chain-planung"),
 "supply-chain-suites": ("Supply-Chain-Suiten", "supply-chain-suiten"),
 "supply-chain-visibility": ("Supply-Chain-Transparenz", "supply-chain-transparenz"),
 "sustainability-management": ("Nachhaltigkeitsmanagement", "nachhaltigkeitsmanagement"),
 "tag-management": ("Tag-Management", "tag-management"),
 "talent-assessment": ("Eignungsdiagnostik", "eignungsdiagnostik"),
 "technical-seo": ("Technisches SEO", "technisches-seo"),
 "time-attendance": ("Zeit- und Anwesenheitserfassung", "zeit-und-anwesenheitserfassung"),
 "tracking": ("Tracking", "tracking"),
 "training-management-systems": ("Schulungsmanagement-Systeme", "schulungsmanagement-systeme"),
 "translation": ("Übersetzung", "uebersetzung"),
 "user-generated-content": ("Nutzergenerierte Inhalte", "nutzergenerierte-inhalte"),
 "vereins-management": ("Vereinsmanagement", "vereinsmanagement"),
 "video-advertising": ("Video-Werbung", "video-werbung"),
 "video-communications": ("Video-Kommunikation", "video-kommunikation"),
 "video-youtube-seo": ("Video- und YouTube-SEO", "video-und-youtube-seo"),
 "virtual-event-platforms": ("Plattformen für virtuelle Events", "plattformen-fuer-virtuelle-events"),
 "virtual-mailbox": ("Virtuelle Postfächer", "virtuelle-postfaecher"),
 "virtual-private-network-vpn": ("VPN", "vpn"),
 "virtual-workspaces": ("Virtuelle Arbeitsplätze", "virtuelle-arbeitsplaetze"),
 "visitor-identification": ("Besucher-Identifikation", "besucher-identifikation"),
 "warenkorb": ("Warenkorb", None),
 "wdf-idf": ("WDF*IDF", "wdf-idf"),
 "web-acceleration": ("Web-Beschleunigung", "web-beschleunigung"),
 "webhosting": ("Webhosting", None),
 "website-personalization": ("Website-Personalisierung", "website-personalisierung"),
 "whatsapp-marketing": ("WhatsApp-Marketing", "whatsapp-marketing"),
 "whatsapp-recruiting": ("WhatsApp-Recruiting", "whatsapp-recruiting"),
 "wireframing": ("Wireframing", "wireframing"),
 "wissensmanagement": ("Wissensmanagement", None),
 "wordpress-hosting": ("WordPress-Hosting", "wordpress-hosting"),
 "workforce-planning": ("Personaleinsatzplanung (strategisch)", "personaleinsatzplanung-strategisch"),
 "workplace-management": ("Arbeitsplatz-Management", "arbeitsplatz-management"),
 "zahlungsdienstleister": ("Zahlungsdienstleister", None),
}

CSV = "docs/verzeichnis/software-kategorien.csv"
rows = list(csv.DictReader(open(CSV, encoding="utf-8"), delimiter=";"))

for r in rows:
    alt = r["slug"]
    if alt in M:
        name, neu = M[alt]
        r["rubrik_final"] = name
        r["slug_final"] = neu or alt
    else:
        r["rubrik_final"] = r["rubrik"]
        r["slug_final"] = alt

# Kollisionspruefung auf den FINALEN Slugs, sonst kollidieren zwei Rubriken still.
soft = [r for r in rows if r["typ"] == "software"]
slugs = [r["slug_final"] for r in soft]
dupes = sorted({s for s in slugs if slugs.count(s) > 1})
geaendert = sum(1 for r in soft if r["slug_final"] != r["slug"])

print(f"Uebersetzt:            {sum(1 for r in rows if r['slug'] in M)}")
print(f"Slug geaendert:        {geaendert}")
print(f"Slug-Kollisionen:      {len(dupes)}")
for d in dupes:
    print("   KOLLISION:", d, "->", [r["rubrik_final"] for r in soft if r["slug_final"] == d])
print(f"Englische Reste:       {sum(1 for r in soft if re.match(r'^[A-Za-z0-9 &/.*()-]+$', r['rubrik_final']) and r['quelle']=='omr' and r['slug'] in M)}")

if dupes:
    sys.exit("Abbruch: Slug-Kollisionen muessen aufgeloest werden, bevor etwas live geht.")

with open(CSV, "w", newline="", encoding="utf-8") as f:
    w = csv.DictWriter(f, fieldnames=["slug","rubrik","prio","quelle","typ","cluster_vorschlag","rubrik_final","slug_final"], delimiter=";")
    w.writeheader()
    w.writerows(rows)
print("\n-> CSV aktualisiert (rubrik_final, slug_final)")
