/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZahlungskanaeleRouteImport } from './routes/zahlungskanaele'
import { Route as SparvorschlaegeRouteImport } from './routes/sparvorschlaege'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ImportRouteImport } from './routes/import'
import { Route as FristenRouteImport } from './routes/fristen'
import { Route as BenachrichtigungenRouteImport } from './routes/benachrichtigungen'
import { Route as AiCreditsRouteImport } from './routes/ai-credits'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KundenIndexRouteImport } from './routes/kunden.index'
import { Route as AbosIndexRouteImport } from './routes/abos.index'
import { Route as KundenKundeIdRouteImport } from './routes/kunden.$kundeId'
import { Route as AbosAboIdRouteImport } from './routes/abos.$aboId'

const ZahlungskanaeleRoute = ZahlungskanaeleRouteImport.update({
  id: '/zahlungskanaele',
  path: '/zahlungskanaele',
  getParentRoute: () => rootRouteImport,
} as any)
const SparvorschlaegeRoute = SparvorschlaegeRouteImport.update({
  id: '/sparvorschlaege',
  path: '/sparvorschlaege',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const FristenRoute = FristenRouteImport.update({
  id: '/fristen',
  path: '/fristen',
  getParentRoute: () => rootRouteImport,
} as any)
const BenachrichtigungenRoute = BenachrichtigungenRouteImport.update({
  id: '/benachrichtigungen',
  path: '/benachrichtigungen',
  getParentRoute: () => rootRouteImport,
} as any)
const AiCreditsRoute = AiCreditsRouteImport.update({
  id: '/ai-credits',
  path: '/ai-credits',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KundenIndexRoute = KundenIndexRouteImport.update({
  id: '/kunden/',
  path: '/kunden/',
  getParentRoute: () => rootRouteImport,
} as any)
const AbosIndexRoute = AbosIndexRouteImport.update({
  id: '/abos/',
  path: '/abos/',
  getParentRoute: () => rootRouteImport,
} as any)
const KundenKundeIdRoute = KundenKundeIdRouteImport.update({
  id: '/kunden/$kundeId',
  path: '/kunden/$kundeId',
  getParentRoute: () => rootRouteImport,
} as any)
const AbosAboIdRoute = AbosAboIdRouteImport.update({
  id: '/abos/$aboId',
  path: '/abos/$aboId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-credits': typeof AiCreditsRoute
  '/benachrichtigungen': typeof BenachrichtigungenRoute
  '/fristen': typeof FristenRoute
  '/import': typeof ImportRoute
  '/onboarding': typeof OnboardingRoute
  '/sparvorschlaege': typeof SparvorschlaegeRoute
  '/zahlungskanaele': typeof ZahlungskanaeleRoute
  '/abos/$aboId': typeof AbosAboIdRoute
  '/kunden/$kundeId': typeof KundenKundeIdRoute
  '/abos/': typeof AbosIndexRoute
  '/kunden/': typeof KundenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-credits': typeof AiCreditsRoute
  '/benachrichtigungen': typeof BenachrichtigungenRoute
  '/fristen': typeof FristenRoute
  '/import': typeof ImportRoute
  '/onboarding': typeof OnboardingRoute
  '/sparvorschlaege': typeof SparvorschlaegeRoute
  '/zahlungskanaele': typeof ZahlungskanaeleRoute
  '/abos/$aboId': typeof AbosAboIdRoute
  '/kunden/$kundeId': typeof KundenKundeIdRoute
  '/abos': typeof AbosIndexRoute
  '/kunden': typeof KundenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-credits': typeof AiCreditsRoute
  '/benachrichtigungen': typeof BenachrichtigungenRoute
  '/fristen': typeof FristenRoute
  '/import': typeof ImportRoute
  '/onboarding': typeof OnboardingRoute
  '/sparvorschlaege': typeof SparvorschlaegeRoute
  '/zahlungskanaele': typeof ZahlungskanaeleRoute
  '/abos/$aboId': typeof AbosAboIdRoute
  '/kunden/$kundeId': typeof KundenKundeIdRoute
  '/abos/': typeof AbosIndexRoute
  '/kunden/': typeof KundenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-credits'
    | '/benachrichtigungen'
    | '/fristen'
    | '/import'
    | '/onboarding'
    | '/sparvorschlaege'
    | '/zahlungskanaele'
    | '/abos/$aboId'
    | '/kunden/$kundeId'
    | '/abos/'
    | '/kunden/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-credits'
    | '/benachrichtigungen'
    | '/fristen'
    | '/import'
    | '/onboarding'
    | '/sparvorschlaege'
    | '/zahlungskanaele'
    | '/abos/$aboId'
    | '/kunden/$kundeId'
    | '/abos'
    | '/kunden'
  id:
    | '__root__'
    | '/'
    | '/ai-credits'
    | '/benachrichtigungen'
    | '/fristen'
    | '/import'
    | '/onboarding'
    | '/sparvorschlaege'
    | '/zahlungskanaele'
    | '/abos/$aboId'
    | '/kunden/$kundeId'
    | '/abos/'
    | '/kunden/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiCreditsRoute: typeof AiCreditsRoute
  BenachrichtigungenRoute: typeof BenachrichtigungenRoute
  FristenRoute: typeof FristenRoute
  ImportRoute: typeof ImportRoute
  OnboardingRoute: typeof OnboardingRoute
  SparvorschlaegeRoute: typeof SparvorschlaegeRoute
  ZahlungskanaeleRoute: typeof ZahlungskanaeleRoute
  AbosAboIdRoute: typeof AbosAboIdRoute
  KundenKundeIdRoute: typeof KundenKundeIdRoute
  AbosIndexRoute: typeof AbosIndexRoute
  KundenIndexRoute: typeof KundenIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zahlungskanaele': {
      id: '/zahlungskanaele'
      path: '/zahlungskanaele'
      fullPath: '/zahlungskanaele'
      preLoaderRoute: typeof ZahlungskanaeleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sparvorschlaege': {
      id: '/sparvorschlaege'
      path: '/sparvorschlaege'
      fullPath: '/sparvorschlaege'
      preLoaderRoute: typeof SparvorschlaegeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fristen': {
      id: '/fristen'
      path: '/fristen'
      fullPath: '/fristen'
      preLoaderRoute: typeof FristenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benachrichtigungen': {
      id: '/benachrichtigungen'
      path: '/benachrichtigungen'
      fullPath: '/benachrichtigungen'
      preLoaderRoute: typeof BenachrichtigungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-credits': {
      id: '/ai-credits'
      path: '/ai-credits'
      fullPath: '/ai-credits'
      preLoaderRoute: typeof AiCreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kunden/': {
      id: '/kunden/'
      path: '/kunden'
      fullPath: '/kunden/'
      preLoaderRoute: typeof KundenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abos/': {
      id: '/abos/'
      path: '/abos'
      fullPath: '/abos/'
      preLoaderRoute: typeof AbosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kunden/$kundeId': {
      id: '/kunden/$kundeId'
      path: '/kunden/$kundeId'
      fullPath: '/kunden/$kundeId'
      preLoaderRoute: typeof KundenKundeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abos/$aboId': {
      id: '/abos/$aboId'
      path: '/abos/$aboId'
      fullPath: '/abos/$aboId'
      preLoaderRoute: typeof AbosAboIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiCreditsRoute: AiCreditsRoute,
  BenachrichtigungenRoute: BenachrichtigungenRoute,
  FristenRoute: FristenRoute,
  ImportRoute: ImportRoute,
  OnboardingRoute: OnboardingRoute,
  SparvorschlaegeRoute: SparvorschlaegeRoute,
  ZahlungskanaeleRoute: ZahlungskanaeleRoute,
  AbosAboIdRoute: AbosAboIdRoute,
  KundenKundeIdRoute: KundenKundeIdRoute,
  AbosIndexRoute: AbosIndexRoute,
  KundenIndexRoute: KundenIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
